name: Build Unity Package

# Controls when the action will run. Triggers the workflow on pushing changes to develop that include 
# updating the 'VersionConstants.cs' since this asset will change only on a new version
on:
  push:
    # Run unit tests anytime any source files change in the external app or Unity integration
    branches: [ develop ]
    paths:
    - 'Unity/Assets/JCMG/Genesis/Scripts/Editor/VersionConstants.cs'
    - '.github/workflows/publish_unity_package.yml'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-latest
    steps:
      # Check out Develop and Release so we can build and perform unit tests on the external solution, Unity
      # Always check out develop so our GitVersion task will complete when building the external solution
      # and ensure fetch-depth is zero to avoid errors with GitVersion
      - uses: actions/checkout@v2
        with:
          ref: 'develop'
          path: './Genesis'
      - uses: actions/checkout@v2
        with:
          ref: 'release/stable'
          path: './Genesis-Release'

      # Retrieve cache for Unity project
      - name: Retrieve Unity Library Cache
        uses: actions/cache@v1.1.0
        with:
          path: './Genesis/Unity/Library'
          key: Library-Genesis-Windows
          restore-keys: |
            Library-Genesis

      # Execute Unity Unit Tests and Upload results
      - name: Run Unity Unit Tests
        uses: game-ci/unity-test-runner@v2.0-alpha-3
        env:
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
          UNITY_SERIAL: ${{ secrets.UNITY_SERIAL }}
        with:
          projectPath: './Genesis/Unity'
          unityVersion: 2019.4.20f1
      - name: Upload Unit Test Results
        uses: actions/upload-artifact@v1
        with:
          name: Test results
          path: artifacts

      # Build Unity Package on Develop branch
      - name: Execute Unity Package Build
        uses: game-ci/unity-builder@v2.0-alpha-6
        env:
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
          UNITY_SERIAL: ${{ secrets.UNITY_SERIAL }}
        with:
          projectPath: './Genesis/Unity'
          unityVersion: 2019.4.20f1
          buildMethod: 'JCMG.PackageTools.Editor.PackageToolsCI.Generate'
          allowDirtyBuild: true

      # Parse package version from Json
      - name: Get Version JSON Property from Package Json
        id: version
        uses: notiz-dev/github-action-json-property@release
        with: 
          path: './Genesis-Release/package.json'
          prop_path: 'version'
      - name: Print Version JSON Property from Package Json
        run: echo "${{steps.version.outputs.prop}}"

      # Check in Unity Package on Release branch
      - name: Add & Commit Release Changes
        uses: EndBug/add-and-commit@v5.1.0
        env:
          # This is necessary in order to push a commit to the repo
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          author_name: Github Action Bot
          cwd: './Genesis-Release'
          branch: 'release/stable'
          message: "v${{steps.version.outputs.prop}}"

      # Tag commit just made with new Nuget package version
      - name: Create Tag
        run: |
          cd './Genesis-Release'
          git tag -a "upm/v${{steps.version.outputs.prop}}" -m "v${{steps.version.outputs.prop}}"
          git push origin --tags